feat: LSDV-4583-1: Introduce `valueList` support
heartexlabs/label-studio-frontend pull request #1173
Opened 2023-02-02 11:37 UTC by nicholasrq

### PR fulfills these requirements
- [x] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [x] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [x] Frontend

### Describe the reason for change
https://labelstudio.aha.io/develop/features/LSDV-4583
https://labelstudio.aha.io/develop/requirements/LSDV-4583-1

#### What is the new behavior?
Since now `Image` supports `valueList` attribute with an array of image URLs. This is the foundation for upcoming multi-image segmentation feature.

#### What is the current behavior?
Previously, Image had support for arrays of images, yet we only supported "layered" mode when regions are shared across all images. With `valueList` it will be possible to perform segmentation on per-image basis.

#### What libraries were added/updated?
None

#### Does this change affect performance?
No

#### Does this change affect security?
No

#### What alternative approaches were there?
None

#### What feature flags were used to cover this change?
`feat-front-lsdv-4583-multi-image-segmentation-short`

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [x] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
Image segmentation

2023-02-02 18:16 UTC, Travis1282 approved these changes

2023-02-02 22:14 UTC, hlomzik requested changes

2023-02-02 22:14 UTC, hlomzik commented on src/components/ImageView/ImageView.js
> +        url: item._value,
should be `currentSrc`

2023-02-02 22:14 UTC, hlomzik commented on src/tags/object/Image.js
> + * @param {string[]} [valuelist]              - List of image urls
And it's not an array of strings, here is just a string, pointing to array in data

2023-02-10 02:45 UTC, hlomzik approved these changes

2023-03-03 17:07 UTC, closed without merging