fix: LSDV-E-35: Manual security updates
heartexlabs/label-studio-frontend pull request #1436
Opened 2023-06-05 19:56 UTC by Travis1282

### PR fulfills these requirements
- [ ] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [ ] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [ ] Frontend

### Describe the reason for change
_(link to issue, supportive screenshots etc.)_

#### What does this fix?
_(if this is a bug fix)_

#### What is the new behavior?
_(if this is a breaking or feature change)_

#### What is the current behavior?
_(if this is a breaking or feature change)_

#### What libraries were added/updated?
_(list all with version changes)_

#### Does this change affect performance?
_(if so describe the impacts positive or negative)_

#### Does this change affect security?
_(if so describe the impacts positive or negative)_

#### What alternative approaches were there?
_(briefly list any if applicable)_

#### What feature flags were used to cover this change?
_(briefly list any if applicable)_

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [ ] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

2023-06-06 17:26 UTC, hlomzik requested changes

2023-06-06 17:26 UTC, hlomzik commented on package.json
> +    "xml2js": "0.6.x",
should not it be `^0.6.0`?

2023-06-06 17:26 UTC, hlomzik commented on e2e/package.json
> +    "node-fetch": "^2.6.7",
`fetch` is not used here as well. please, remove it

2023-06-06 17:26 UTC, hlomzik commented on package.json
> +    "babel-loader": "8.2.2",
do we really need to make version fixed here?

2023-06-07 14:09 UTC, hlomzik requested changes

2023-06-07 17:00 UTC, Travis1282 commented on package.json
> +  },
yea dependabot wants this version. so we should make the one in dm match? 
https://github.com/heartexlabs/label-studio-frontend/security/dependabot/84

2023-06-07 18:40 UTC, bmartel commented on package.json
> +    "xml2js": "0.6.x",
```suggestion
    "xml2js": "^0.6.0",
```

2023-06-07 18:41 UTC, bmartel approved these changes

2023-06-07 20:38 UTC, closed without merging