feat: LSDV-5296: Scroll container max height
heartexlabs/label-studio-frontend pull request #1469
Opened 2023-06-19 14:04 UTC by Travis1282

### PR fulfills these requirements
- [X] Commit message(s) and PR title follows the format `[fix|feat|ci|chore|doc]: TICKET-ID: Short description of change made` ex. `fix: DEV-XXXX: Removed inconsistent code usage causing intermittent errors`
- [ ] Tests for the changes have been added/updated (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [X] Best efforts were made to ensure docs/code are concise and coherent (checked for spelling/grammatical errors, commented out code, debug logs etc.)
- [X] Self-reviewed and ran all changes on a local instance (for bug fixes/features)

#### Change has impacts in these area(s)
_(check all that apply)_
- [ ] Product design
- [X] Frontend

### Describe the reason for change
Add maxheight as a config attribute with a default of 500px and style scrolling window

#### What does this fix?
N/A

#### What is the new behavior?
The config attribute defines the maximum height of the scrolling window 

#### What is the current behavior?
it takes up as much space as it's contents will allow 

#### What libraries were added/updated?
none

#### Does this change affect performance?
no

#### Does this change affect security?
no

#### What alternative approaches were there?
we could have used flex box or javascript to calc the available space 

#### What feature flags were used to cover this change?
fflag_feat_front_lsdv_e_278_contextual_scrolling_short

### Does this PR introduce a breaking change?
_(check only one)_
- [ ] Yes, and covered entirely by feature flag(s)
- [ ] Yes, and covered partially by feature flag(s)
- [X] No
- [ ] Not sure (briefly explain the situation below)

### What level of testing was included in the change?
_(check all that apply)_
- [ ] e2e
- [ ] integration
- [ ] unit

### Which logical domain(s) does this change affect?
_(for bug fixes/features, be as precise as possible. ex. Authentication, Annotation History, Review Stream etc.)_

2023-06-19 20:57 UTC, hlomzik approved these changes

2023-06-19 20:57 UTC, hlomzik commented on src/tags/object/Paragraphs/model.js
> + * @param {string} [maxheight]           - Maximum height of the paragraph container
camelCase and default value

2023-06-19 20:57 UTC, hlomzik commented on src/tags/object/Paragraphs/Paragraphs.module.scss
> +  border: 1px solid rgba(137, 128, 152, 0.16);
can we move this to constants?

2023-06-19 20:57 UTC, hlomzik commented on src/utils/feature-flags.ts
> +export const FF_LSDV_E_278 = 'fflag_feat_front_lsdv_e_278_contextual_scrolling_short';
please, reorder it to be sorted

2023-06-20 12:05 UTC, hlomzik requested changes

2023-06-20 14:03 UTC, Travis1282 commented on src/utils/feature-flags.ts
> +export const FF_LSDV_E_278 = 'fflag_feat_front_lsdv_e_278_contextual_scrolling_short';
ah thanks

2023-06-20 14:19 UTC, Travis1282 commented on src/tags/object/Paragraphs/HtxParagraphs.js
> +      { scrollContainerHeight: height < minHeight ? minHeight : height },
good thinking

2023-06-20 14:31 UTC, Travis1282 commented on src/tags/object/Paragraphs/model.js
> + * @param {string} [maxheight]           - Maximum height of the paragraph container
ok, isn't the default flase here?

2023-06-21 15:27 UTC, hlomzik approved these changes

2023-06-21 15:27 UTC, hlomzik commented
/git merge master

2023-06-21 16:44 UTC, merged