update tag docs
heartexlabs/label-studio-frontend pull request #265
Opened 2021-09-01 23:41 UTC by smoreface

- Add more use case details 
- Add info about which data types are supported
- Improve meta_title and meta_description
- Correct some typos 
- Add example descriptions

2021-09-01 23:42 UTC, smoreface commented on src/tags/control/Choice.js
> + * The Choice tag represents a single choice for annotations. Use for simple classification tasks where annotators must provide one answer.
correct?

2021-09-01 23:43 UTC, smoreface commented on src/tags/control/HyperTextLabels.js
> +  .model("HyperTextLabelsModel", {
fixed this seeming typo

2021-09-01 23:43 UTC, smoreface commented on src/tags/control/KeyPointLabels.js
> + * The KeyPointLabels tag creates labeled keypoints. Use to apply labels to identified key points when performing semantic segmentation.
correct use case?

2021-09-01 23:43 UTC, smoreface commented on src/tags/control/KeyPointLabels.js
> +  .model("KeyPointLabelsModel", {
fixed this typo

2021-09-01 23:43 UTC, smoreface commented on src/tags/control/Label.js
> + * Label tag represents a single label. Use to assign a single label to regions in a task, or with the Labels tag to provide many labels.
accurate?

2021-09-01 23:44 UTC, smoreface commented on src/tags/control/Number.js
> + * Use with the following data types: audio, image, text, time series, video
accurate?

2021-09-01 23:45 UTC, smoreface commented on src/tags/control/ParagraphLabels.js
> +  .model("ParagraphLabelsModel", {
fixed this typo

2021-09-01 23:46 UTC, smoreface commented on src/tags/control/Ranker.js
> + * Use the Ranker tag to rank the results from models. This tag uses the "prediction" field from a labeling task instead of the "data" field to display content for labeling on the interface. Carefull
since line breaks in the comments aren't well-handled in the md changeover, this is now the longest line ever, i'm sorry

2021-09-01 23:57 UTC, smoreface commented on src/tags/control/Taxonomy.js
> + * Use with the following data types: audio, image, text, time series, video
accurate? does it only work for choices or also for labels?

2021-09-01 23:57 UTC, smoreface commented on src/tags/object/Paragraphs.js
> + * The Paragraphs tag displays paragraphs of text on the labeling interface. Use to label dialogue transcripts for NLP and NER projects.
accurate?

2021-09-01 23:58 UTC, smoreface commented on src/tags/object/Text.js
> + * Every space in the text sample is counted when calculating result offsets, for example for NER labeling tasks.
accurate?

2021-09-01 23:58 UTC, smoreface commented on src/tags/visual/Dialog.js
> + * The Dialog tag renders a dialog box on a task with instructions or other content that you define.
Is this deprecated / intentionally hidden? (xss?)

2021-09-01 23:59 UTC, smoreface commented on src/tags/visual/Filter.js
> + * Use the Filter tag to add a filter search for a large number of labels. Use with the Labels tag.
does it work with other tags?

2021-09-01 23:59 UTC, smoreface commented on src/tags/visual/Header.js
>   *   <Header name="text-1" value="Please select the class" />
name argument here isn't listed in the params -- should it be?

2021-09-01 23:59 UTC, smoreface commented on src/tags/visual/Style.js
> + * Use the Style tag to apply CSS styles to the labeling interface.
I have a ticket to improve the details here

2021-09-02 14:06 UTC, hlomzik requested changes

2021-09-02 22:25 UTC, smoreface commented on src/tags/control/Choice.js
>   * @param {string} [alias]     - Alias for the label
Fixed!

2021-09-02 22:58 UTC, smoreface commented on src/tags/control/TextArea/TextArea.js
>   * @param {string=} [maxSubmissions]       - Maximum number of submissions
@hlomzik I'd like to improve these three params but I don't know enough about them. Can you help?

2021-09-02 23:00 UTC, smoreface commented on src/tags/object/AudioPlus.js
> + * The AudioPlus tag plays audio and shows its waveform. Use for advanced audio annotation tasks where you want to see the waveform and manipulate audio during annotation.
Perfect, updated!

2021-09-02 23:00 UTC, smoreface commented on src/tags/control/List.js
>   * @param {string} name                        - Name of group
I'd like to add more details to these params too but I don't understand them. Can you help?

2021-09-03 00:12 UTC, smoreface commented
@hlomzik  any idea where the code/doc for the DateTime tag is, and if there is a way to document the user-contributed Repeater tag? I don't see a repeater.js file for it in the repo or the PR so not sure if that's possible.

2021-09-03 11:00 UTC, hlomzik commented
> @hlomzik any idea where the code/doc for the DateTime tag is

`DateTime` is in PR — #257 so it should not be published now. But I'll appreciate if you can fix docs right in the PR!


> if there is a way to document the user-contributed Repeater tag?

Oh, it's complicated. This tag is a virtual tag, it's used only somewhere deep in the code. I'll add some doc for it a bit later somehow...

2021-09-09 00:17 UTC, makseq approved these changes

2021-09-09 15:18 UTC, merged