[fix] Add observing of image size for special cases
heartexlabs/label-studio-frontend pull request #340
Opened 2021-11-10 02:05 UTC by Gondragos

This should fix the canvas resizing when the scrollbar appears.

2021-11-11 09:58 UTC, nicholasrq requested changes

2021-11-11 09:58 UTC, nicholasrq commented on src/components/ImageView/ImageView.js
> +import ResizeObserver from "resize-observer-polyfill";
Remove imoprt

2021-11-11 10:05 UTC, hlomzik commented on src/components/ImageView/ImageView.js
> +      this.resizeObserver = new ResizeObserver(this.onResize);
Can you make a fallback with empty methods for older browsers

2021-11-11 10:21 UTC, Gondragos commented on src/components/ImageView/ImageView.js
> +import ResizeObserver from "resize-observer-polyfill";
Replaced with fallback

2021-11-11 11:46 UTC, nicholasrq approved these changes

2021-11-15 08:11 UTC, nicholasrq approved these changes

2021-11-18 15:04 UTC, niklub approved these changes

2021-11-18 15:41 UTC, merged