[ext] Add displaing created date for annotations
heartexlabs/label-studio-frontend pull request #349
Opened 2021-11-12 12:52 UTC by Gondragos

2021-11-15 09:16 UTC, hlomzik requested changes

2021-11-15 09:16 UTC, hlomzik commented on src/common/TimeAgo/TimeAgo.js
> +import { format, formatDistanceToNow } from "date-fns";
imports at the most top level

2021-11-15 09:16 UTC, hlomzik commented on src/common/TimeAgo/TimeAgo.js
> +function * scheduleGen(value = 0) {
comments, please. and typescript to understand resulting values

2021-11-15 09:16 UTC, hlomzik commented on src/common/TimeAgo/TimeAgo.js
> +function * scheduleGen(value = 0) {
and I think it would be mush simpler to just create a calculation function like `getNextTick(timePassed)`

2021-11-18 08:58 UTC, hlomzik approved these changes

2021-11-18 08:58 UTC, hlomzik commented on src/common/TimeAgo/TimeAgo.tsx
> +  [Number.MAX_SAFE_INTEGER, 30 * MINS], // to 30 seconds with 30 seconds step
30 minutes step till the infinity :)

2021-11-29 07:56 UTC, nicholasrq approved these changes

2021-12-28 18:01 UTC, merged