Run npm audit action
heartexlabs/label-studio-frontend pull request #367
Opened 2021-11-25 12:08 UTC by niklub

2021-11-25 12:29 UTC, farioas commented on .github/workflows/main.yml
> +        run: npm ci
- name: Setup node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "${{ env.NODE }}"

      - name: Upgrade npm
        run: npm install -g npm@7

2021-11-25 14:11 UTC, nicholasrq requested changes

2021-11-25 14:11 UTC, nicholasrq commented on package.json
> +    "npm": "^8.1.4",
this is unnecessary

2021-11-26 09:01 UTC, farioas requested changes
Please rename `main.yml` to `npm_audit.yml`

2021-11-26 09:17 UTC, nicholasrq approved these changes

2021-11-26 12:05 UTC, farioas approved these changes

2021-12-08 18:04 UTC, merged