DEV-1262: Improving react rendering performance for video tag
heartexlabs/label-studio-frontend pull request #390
Opened 2021-12-10 06:02 UTC by nicholasrq

2021-12-10 11:01 UTC, hlomzik approved these changes

2021-12-13 13:00 UTC, hlomzik requested changes

2021-12-13 16:14 UTC, nicholasrq commented on src/components/VideoCanvas/VirtualCanvas.tsx
> +    <div ref={rootRef as LegacyRef<HTMLDivElement>}/>
because @types/react-dom is weird and doesn't properly handle useRef() MutableRef type

2021-12-13 18:58 UTC, makseq approved these changes

2021-12-13 18:58 UTC, merged