feat: DEV-1602: Update Table Tag to show csv data
heartexlabs/label-studio-frontend pull request #478
Opened 2022-02-09 14:29 UTC by superdev808

2022-02-09 14:56 UTC, hlomzik requested changes
Also don't update lock-files unless you change `package.json`

2022-02-09 15:05 UTC, superdev808 commented on src/env/development.js
> +import { TableCsv } from "../examples/table_csv";
not sure what this comment means.

2022-02-10 06:53 UTC, hlomzik approved these changes

2022-02-10 06:53 UTC, hlomzik commented on src/tags/object/Table.js
> +  observer(({ _, item }) => {
this is object, so `_` is redundant

2022-02-10 06:53 UTC, hlomzik commented on src/tags/object/Table.js
> +      console.log(originData);
the last one left :)

2022-02-10 06:53 UTC, hlomzik commented
and resolve conflict please, any version is good, they are the same

2022-02-16 18:12 UTC, nicholasrq approved these changes

2022-02-16 18:16 UTC, merged