fix: Video improvements
heartexlabs/label-studio-frontend pull request #497
Opened 2022-02-16 07:16 UTC by nicholasrq

Fixes:

- DEV-1323
- DEV-1245
- DEV-1267
- DEV-1272
- DEV-1515
- DEV-1271
- DEV-1692

2022-04-08 10:22 UTC, hlomzik requested changes

2022-04-12 13:25 UTC, hlomzik requested changes

2022-04-12 13:25 UTC, hlomzik commented on src/regions/ImageRegion.js
> -    get editable() {
we also use this field

2022-04-12 13:47 UTC, nicholasrq commented on src/regions/EditableRegion.js
> +export const EditableRegion = types
done

2022-04-12 14:33 UTC, hlomzik approved these changes

2022-04-12 14:56 UTC, merged