fix: DEV-1833: Prop whenChoiceValue working as expected
heartexlabs/label-studio-frontend pull request #703
Opened 2022-06-10 19:40 UTC by juliosgarbi

2022-06-10 20:16 UTC, bmartel requested changes

2022-06-10 20:16 UTC, bmartel commented on src/mixins/Visibility.js
> +      }else if (self.whenchoicevalue){
```suggestion
      } else if (self.whenchoicevalue) {
```

2022-06-10 20:16 UTC, bmartel commented on src/mixins/Visibility.js
> +          if (choices.selectedValues && choices.selectedValues().length){
```suggestion
          const choicesList = choices?.selectedValues?.()
          if (choicesList?.length) {
```

2022-06-10 20:16 UTC, bmartel commented on src/mixins/Visibility.js
> +            const choicesList = choices.selectedValues();
```suggestion
```

2022-06-13 17:13 UTC, Travis1282 approved these changes

2022-06-17 20:33 UTC, merged