feat: DEV-2755: Regions list grouped by labels with persistent & ordered collapse
heartexlabs/label-studio-frontend pull request #761
Opened 2022-07-20 14:03 UTC by yyassi-heartex

2022-07-20 14:49 UTC, juliosgarbi requested changes
Features must be behind feature flags also there is some inconsistency in the spacing between '( )' some places have some not

2022-07-20 15:04 UTC, juliosgarbi submitted a review, later dismissed
LGTM!

2022-07-21 15:32 UTC, juliosgarbi approved these changes
LGTM

2022-07-21 15:49 UTC, bmartel requested changes

2022-07-21 15:49 UTC, bmartel commented on src/components/Entities/LabelList.js
> +  const expandedKeys = treeData.filter( item => !collapsedPos.includes( item.pos ) ).map( item => item.key ) ?? [];
probably should put any of the new additional functionality behind the FF.

the `Tree` props `expandedKeys` and `onExpand` will have the new behaviour by default right now.

2022-07-21 16:44 UTC, bmartel approved these changes

2022-08-05 19:06 UTC, yyassi-heartex commented
/git merge develop

2022-08-19 08:45 UTC, merged