fix: DEV-2930: Fix collapsed texts for TextArea
heartexlabs/label-studio-frontend pull request #765
Opened 2022-07-21 19:02 UTC by nicholasrq

Also fixes DEV-2928

2022-07-21 19:11 UTC, bmartel requested changes
Formatting, rest looks good.

2022-07-21 19:11 UTC, bmartel commented on src/components/SidePanels/DetailsPanel/RegionDetails.tsx
> +    <Text mark >
```suggestion
    <Text mark>
```

2022-07-21 19:11 UTC, bmartel commented on src/components/SidePanels/DetailsPanel/RegionDetails.tsx
> +    <Text mark >
```suggestion
    <Text mark>
```

2022-07-21 19:18 UTC, bmartel approved these changes

2022-07-22 01:36 UTC, hlomzik requested changes

2022-07-22 01:36 UTC, hlomzik commented on src/components/SidePanels/DetailsPanel/RegionDetails.tsx
> +const CnoicesResult: FC<{mainValue: string[]}> = observer(({ mainValue }) => {
typo: ChoicesResult

2022-07-22 11:24 UTC, hlomzik approved these changes

2022-07-22 11:24 UTC, merged