fix: DEV-2958: Fix NER region text not displaying in Details
heartexlabs/label-studio-frontend pull request #771
Opened 2022-07-22 17:14 UTC by nicholasrq

2022-07-22 20:49 UTC, bmartel requested changes
looks good otherwise

2022-07-22 20:49 UTC, bmartel commented on src/components/SidePanels/DetailsPanel/RegionDetails.tsx
> +  console.log(result);
forgot a console.log

2022-07-22 21:01 UTC, bmartel approved these changes

2022-07-24 16:40 UTC, hlomzik approved these changes

2022-08-02 10:05 UTC, merged