fix: DEV-2934: Fix Audio resizing behavior
heartexlabs/label-studio-frontend pull request #772
Opened 2022-07-22 19:09 UTC by nicholasrq

Audio doesn't properly react to the layout resize. It causes regions to be shifted when resize happens when  zoom is 1.

2022-07-22 20:54 UTC, bmartel requested changes
looks great, just a line of code left over

2022-07-22 20:54 UTC, bmartel commented on src/components/Timeline/Views/Wave/Wave.tsx
> +        // if (wsi) wsi.zoom(storedPosition.current.zoom);
forgot some commented out code here

2022-07-22 21:00 UTC, bmartel approved these changes

2022-07-24 16:43 UTC, hlomzik approved these changes

2022-08-01 14:38 UTC, merged