fix: DEV-2578: Undo keypoints when create new polygon
heartexlabs/label-studio-frontend pull request #778
Opened 2022-07-25 22:14 UTC by juliosgarbi

2022-07-26 22:33 UTC, hlomzik requested changes

2022-07-26 22:33 UTC, hlomzik commented on src/regions/PolygonRegion.js
> +      undoRedoPoints(undo = true){
spacing

2022-07-26 22:33 UTC, hlomzik commented on src/mixins/DrawingTool.js
> +  hotkeys.addNamed("polygon:redo", () => self.getCurrentArea()?.undoRedoPoints(false));
you should always remove hotkeys on destory, [check Tool.js](https://github.com/heartexlabs/label-studio-frontend/blob/master/src/components/Toolbar/Tool.js#L82-L100) for example or search for `hotkey.` usages in the project.

2022-07-26 22:33 UTC, hlomzik commented on src/regions/PolygonRegion.js
> +      undoRedoPoints(undo = true){
there are no common logic, so it would be more clear to split this method in two: undoPoint/redoPoint

2022-07-26 22:33 UTC, hlomzik commented on src/stores/AppStore.js
> +        if (!annotation.isDrawing) annotation.undo();
actually these two lines can be very helpful!

2022-07-28 16:49 UTC, Travis1282 approved these changes

2022-07-29 19:25 UTC, hlomzik requested changes
main question, as usual — feature flags? ;)

2022-07-29 19:31 UTC, hlomzik submitted a review, later dismissed

2022-07-29 19:31 UTC, hlomzik commented on src/components/ImageView/ImageView.js
> +        if (annotation.isDrawing) item.drawingRegion.undoPoints();
`DrawingRegion` is used not only in polygons, so you can get an error in this line. but I think it would be enough to just add `?.`

2022-07-29 19:31 UTC, hlomzik commented on src/regions/PolygonRegion.js
> +        if(_historyPoints[self.points.length])
fix spacing and add braces in this methods; also it's better to move `_historyPoints[self.points.length]` to a var

2022-08-05 19:16 UTC, Travis1282 approved these changes

2022-08-12 13:04 UTC, merged