feat: DEV-2717: Audio Controls
heartexlabs/label-studio-frontend pull request #829
Opened 2022-09-02 17:09 UTC by juliosgarbi

New UI for audio controls

2022-09-02 18:18 UTC, bmartel requested changes
Looks good, couple changes to be made. Also I am thinking when we go to integrate the new lib with this work, we are going to want to change how we render controls. The audio information can be spammy, so we want to make double sure we aren't causing needless re-renders in react components. (probably implement some memoization and useCallbacks etc.)

2022-09-02 18:18 UTC, bmartel commented on src/components/Timeline/Controls.tsx
> +        )}
Probably should swap this around to being in the positive tense as it reads a bit easier.
```suggestion
        {isFF(FF_DEV_2715) ? (
          <TimeDurationControl
            startTime={0}
            endTime={duration}
            minTime={0}
            maxTime={duration}
            currentTime={currentTime}
            onChangeStartTime={onTimeUpdateChange}
          />
        ) : (
          <TimeDisplay
            currentTime={currentTime}
            duration={duration}
            length={length}
            position={position}
            framerate={frameRate}
            formatPosition={formatPosition}
          />
        )}
```

2022-09-02 18:18 UTC, bmartel commented on src/components/Timeline/Controls.tsx
> +
```suggestion
```

2022-12-06 15:05 UTC, juliosgarbi commented
it's already in fb-dev-2715

2022-12-06 15:05 UTC, closed without merging