fix: DEV-3298: Repeater performance improvement
heartexlabs/label-studio-frontend pull request #840
Opened 2022-09-08 23:27 UTC by juliosgarbi

2022-09-09 13:03 UTC, bmartel requested changes
Looks good, some cleanup to do on Pagination component.

2022-09-09 19:21 UTC, bmartel requested changes
Just a couple changes to the descriptions of the hotkeys to match the usage. Rest is ready to go.

2022-09-09 19:21 UTC, bmartel commented on src/core/settings/keymap.json
> +    "description": "Hop Forward"
```suggestion
    "description": "Next Page"
```

2022-09-09 19:21 UTC, bmartel commented on src/core/settings/keymap.json
> +    "description": "Hop Forward"
```suggestion
    "description": "Previous Page"
```

2022-09-10 10:03 UTC, bmartel approved these changes

2022-09-14 20:19 UTC, bmartel approved these changes
Works well, nice one.

2022-09-15 01:50 UTC, hlomzik requested changes

2022-09-15 01:50 UTC, hlomzik commented on src/tags/visual/Repeater.js
> + * @param {default|pagination} [mode]  - Select display mode between default and paginated
I'd name it "list" maybe?

2022-09-15 01:50 UTC, hlomzik commented on src/tags/object/PagedView.js
> +    setTimeout(() => {
but it's still here, in a next tick. why?

2022-09-15 13:30 UTC, juliosgarbi commented on src/core/settings/keymap.json
> +    "description": "Hop Forward"
This file is outdated

2022-09-15 13:30 UTC, juliosgarbi commented on src/tags/visual/Repeater.js
> + * @param {default|pagination} [mode]  - Select display mode between default and paginated
Done

2022-09-15 14:09 UTC, merged