fix: DEV-3389: Display indices in the regions list
heartexlabs/label-studio-frontend pull request #843
Opened 2022-09-12 21:09 UTC by nicholasrq

2022-09-12 21:46 UTC, bmartel requested changes
couple leftover consoles, implementation looks good

2022-09-12 21:46 UTC, bmartel commented on src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
> +  console.log({ regionsTree });
leftover console 
```suggestion
```

2022-09-12 21:46 UTC, bmartel commented on src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
> +  console.log(props.entity);
```suggestion
```

2022-09-12 21:51 UTC, hlomzik requested changes

2022-09-12 21:51 UTC, hlomzik commented on src/components/SidePanels/OutlinerPanel/OutlinerTree.tsx
> +          icon={({ entity, isNotLabel }: any) => <NodeIconComponent node={entity}/>}
not used

2022-09-12 21:51 UTC, hlomzik commented on src/stores/RegionStore.js
> +          isNotLabel: true,
what's this? is it always true? or is it only for "group by label" mode? so I'd suggest to rename it

2022-09-13 12:42 UTC, bmartel approved these changes

2022-09-14 16:02 UTC, merged