fix: DEV-1943: After awhile, shapes disappear
heartexlabs/label-studio-frontend pull request #852
Opened 2022-09-14 20:29 UTC by yyassi-heartex

2022-09-14 20:58 UTC, bmartel requested changes
Looks good, couple minor observations.

2022-09-14 20:58 UTC, bmartel commented on src/components/Toolbar/Tool.js
> +        if (!(tool?.annotation?.isDrawing ?? false))
```suggestion
        if (!(tool?.annotation?.isDrawing))
```

2022-09-14 20:58 UTC, bmartel commented on src/components/Toolbar/Tool.js
> +        if (!(tool?.annotation?.isDrawing ?? false))
its already boolean coerced, no need for the null coalesce.

2022-09-14 20:58 UTC, bmartel commented on src/components/Toolbar/Tool.js
> +  const isAnnotationDrawing = tool?.annotation?.isDrawing ?? false;
```suggestion
  const isAnnotationDrawing = tool?.annotation?.isDrawing;
```
same here

2022-09-14 21:38 UTC, bmartel approved these changes
Looks good, checked it and it works well 💪

2022-09-15 16:57 UTC, hlomzik commented
> /git merge develop
there is no `develop` in LSF :)

2022-09-15 16:57 UTC, hlomzik commented
/git merge master

2022-09-15 16:58 UTC, yyassi-heartex commented
> > /git merge develop
> 
> there is no `develop` in LSF :)

lol yep as soon as i typed it im like "oh right" so i merged manually lol

2022-09-16 14:55 UTC, yyassi-heartex commented
/git merge master

2022-09-22 13:31 UTC, bmartel approved these changes
Just the one commented out bit needs to get removed, approving this on that removal.

2022-09-22 13:31 UTC, bmartel commented on src/tools/Base.js
> +      // get isDrawingTool() {
I think this was meant to be removed

2022-09-22 13:33 UTC, yyassi-heartex commented on src/tools/Base.js
> +      // get isDrawingTool() {
you are right - i'll get rid of it

2022-09-26 12:10 UTC, merged