fix: DEV-3350: Video object boundaries
heartexlabs/label-studio-frontend pull request #866
Opened 2022-09-21 18:14 UTC by nicholasrq

2022-09-21 18:50 UTC, bmartel requested changes
The code looks good, can we clean up all these commented out pieces of code? I am going to take another pass over this again as well just as its quite dense.

2022-09-21 18:50 UTC, bmartel commented on src/tags/object/Video/Rectangle.tsx
> +    // limitTransformations(e.target);
```suggestion
```

2022-09-21 18:50 UTC, bmartel commented on src/tags/object/Video/Rectangle.tsx
> +      // dragBoundFunc={dragBoundFunc}
```suggestion
```

2022-09-21 18:50 UTC, bmartel commented on src/tags/object/Video/VideoRegions.js
> +        // if (!reg.annotation.editable || reg.parent.getSkipInteractions()) return;
```suggestion
```

2022-09-21 18:50 UTC, bmartel commented on src/tags/object/Video/VideoRegions.js
>      // const { offsetX: x, offsetY: y } = e.evt;
```suggestion
```

2022-09-21 18:50 UTC, bmartel commented on src/tags/object/Video/HtxVideo.js
>  // const hotkeys = Hotkey("Video", "Video Annotation");
```suggestion
```

2022-09-21 18:50 UTC, bmartel commented on src/components/ImageView/ImageView.js
>        // item.freezeHistory();
```suggestion
```

2022-09-21 19:04 UTC, bmartel approved these changes

2022-09-21 19:26 UTC, hlomzik requested changes

2022-09-21 19:26 UTC, hlomzik commented on src/tags/object/Video/tools.ts
> +      node.height(Math.max(3, node.height() * scaleY));
magical number. we already have constants for minimal rect size

2022-09-21 19:26 UTC, hlomzik commented on src/tags/object/Video/TransformTools.ts
> +export const onDragMove = (workingArea: WorkingArea, enabled = true) => function(this: Transformer, e: KonvaEventObject<DragEvent>) {
it returns function, so name should reflect this — like `createOnDragMoveHandler` or maybe something shorter

2022-09-21 19:26 UTC, hlomzik commented on src/tags/object/Video/TransformTools.ts
> +export const boundBoxFunction = (workingArea: WorkingArea, enabled = true) => (oldBox: Box, newBox: Box) => {
and that's opposite — it returns bbox, so just `getBBox` or smth

2022-09-21 19:26 UTC, hlomzik commented on src/tags/object/Video/TransformTools.ts
> +export const getTotalBox = (boxes: {
whole? but doesn't matter

2022-09-21 19:26 UTC, hlomzik commented on src/utils/feature-flags.ts
> + * @link https://app.launchdarkly.com/default/production/features/fflag_fix_front_dev_3350_restrict_drawing_area_short
Not sure it's a good idea to hardcode such links, especially in opensource. This page can be easily found by ff name and the whole comment is too big. I'd suggest to use simple one-line comment.

2022-09-22 02:49 UTC, hlomzik approved these changes

2022-11-04 19:05 UTC, yyassi-heartex reviewed
really minor tweaks, removing the commented out code + reusing the min rectangle size const as @hlomzik suggested then we should be good to go

2022-11-04 19:05 UTC, yyassi-heartex commented on public/index.html
> +              //"annotations:history",
```suggestion
```

2022-11-04 20:08 UTC, yyassi-heartex approved these changes

2022-11-15 10:45 UTC, merged