feat: DEV-3391: Render real Annotations in View All
heartexlabs/label-studio-frontend pull request #928
Opened 2022-10-25 10:04 UTC by hlomzik

2022-10-25 12:41 UTC, bmartel requested changes

2022-10-25 12:41 UTC, bmartel commented on src/core/Tree.tsx
> +  });
Do we have to traverse this twice? Can these not be done in one traversal?

2022-10-25 12:41 UTC, bmartel commented on src/stores/Annotation/Annotation.js
> +    console.log('ROOT', sn, root);
```suggestion
```

2022-10-25 12:41 UTC, bmartel commented on src/stores/Annotation/Annotation.js
> +    // },
Can we clean these up, or is this still needed for something?

2022-10-25 12:41 UTC, bmartel commented on src/stores/Annotation/store.js
> +      // if (self.root) return;
```suggestion
```

2022-10-25 12:41 UTC, bmartel commented on src/stores/Annotation/store.js
> +      // const objects = [];
Probably can remove these if we are performing this work elsewhere now.

2022-10-25 12:41 UTC, bmartel commented on src/stores/Annotation/store.js
> +      // });
```suggestion
```

2022-10-25 12:41 UTC, bmartel commented on src/stores/Annotation/store.js
> +      // self.toNames = toNames;
```suggestion
```

2022-10-28 18:35 UTC, bmartel commented
So far things have been looking good, I noticed when reviewing locally the code that this also appears to have issues with Relations model which you might want to take a look at:

![Screen Shot 2022-10-28 at 1 19 48 PM](https://user-images.githubusercontent.com/2242258/198708120-585860cf-03cc-44b5-a4f5-d4d605a44c6c.png)
![Screen Shot 2022-10-28 at 1 20 31 PM](https://user-images.githubusercontent.com/2242258/198708125-35218f5b-2de3-44f8-894c-c37625f4d03f.png)

2022-10-28 19:06 UTC, bmartel commented
Also found issues with Regions not submitting/loading correctly with Video+Audio.

https://user-images.githubusercontent.com/2242258/198713246-9677632c-309d-4010-9acf-f58af5666ccf.mov

2022-10-28 19:16 UTC, bmartel commented
Also issues with Video Rectangles

https://user-images.githubusercontent.com/2242258/198714839-b6da7099-f1e3-462e-a890-b6d36ffc58ca.mov


```
Annotation.js:1014 TypeError: Cannot read properties of null (reading 'toNames')
    at Object.states (Video.js:91:1)
    at Object.deserializeSingleResult (Annotation.js:1084:1)
    at executeAction (mobx.module.js:928:1)
    at bound deserializeSingleResult (mobx.module.js:915:1)
    at runMiddleWares (mobx-state-tree.module.js:2593:1)
    at runWithActionContext (mobx-state-tree.module.js:2456:1)
    at Object.res (mobx-state-tree.module.js:2483:1)
    at Annotation.js:990:1
    at Array.forEach (<anonymous>)
    at Object.deserializeResults (Annotation.js:983:1)
deserializeResults @ Annotation.js:1014
executeAction @ mobx.module.js:928
bound deserializeResults @ mobx.module.js:915
runMiddleWares @ mobx-state-tree.module.js:2593
runWithActionContext @ mobx-state-tree.module.js:2456
res @ mobx-state-tree.module.js:2483
(anonymous) @ AppStore.js:644
setHistory @ AppStore.js:641
executeAction @ mobx.module.js:928
bound setHistory @ mobx.module.js:915
runMiddleWares @ mobx-state-tree.module.js:2593
runWithActionContext @ mobx-state-tree.module.js:2456
res @ mobx-state-tree.module.js:2483
(anonymous) @ DataManager.js:415
Promise.then (async)
(anonymous) @ DataManager.js:406
(anonymous) @ dm-sdk.js:357
invoke @ dm-sdk.js:357
(anonymous) @ lsf-sdk.js:646
(anonymous) @ events.ts:33
invoke @ events.ts:33
selectAnnotation @ store.js:133
executeAction @ mobx.module.js:928
bound selectAnnotation @ mobx.module.js:915
runMiddleWares @ mobx-state-tree.module.js:2593
runWithActionContext @ mobx-state-tree.module.js:2456
res @ mobx-state-tree.module.js:2483
(anonymous) @ AppStore.js:618
initializeStore @ AppStore.js:615
executeAction @ mobx.module.js:928
bound initializeStore @ mobx.module.js:915
runMiddleWares @ mobx-state-tree.module.js:2593
runWithActionContext @ mobx-state-tree.module.js:2456
res @ mobx-state-tree.module.js:2483
setLSFTask @ lsf-sdk.js:296
(anonymous) @ AppStore.js:214
(anonymous) @ mobx-state-tree.module.js:3631
executeAction @ mobx.module.js:928
<unnamed action> @ mobx.module.js:915
runMiddleWares @ mobx-state-tree.module.js:2593
runWithActionContext @ mobx-state-tree.module.js:2456
wrap @ mobx-state-tree.module.js:3617
onFulfilled @ mobx-state-tree.module.js:3631
Promise.then (async)
next @ mobx-state-tree.module.js:3671
onFulfilled @ mobx-state-tree.module.js:3640
asyncActionInit @ mobx-state-tree.module.js:3623
executeAction @ mobx.module.js:928
asyncActionInit @ mobx.module.js:915
runMiddleWares @ mobx-state-tree.module.js:2593
runWithActionContext @ mobx-state-tree.module.js:2456
(anonymous) @ mobx-state-tree.module.js:3626
flowSpawner @ mobx-state-tree.module.js:3619
executeAction @ mobx.module.js:928
bound flowSpawner @ mobx.module.js:915
runMiddleWares @ mobx-state-tree.module.js:2593
runWithActionContext @ mobx-state-tree.module.js:2456
res @ mobx-state-tree.module.js:2483
nextAction @ AppStore.js:306
startLabeling @ AppStore.js:325
executeAction @ mobx.module.js:928
bound startLabeling @ mobx.module.js:915
runMiddleWares @ mobx-state-tree.module.js:2593
runWithActionContext @ mobx-state-tree.module.js:2456
res @ mobx-state-tree.module.js:2483
(anonymous) @ DataView.js:126
onClick @ Table.js:66
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
ErrorMessage.js:5 TypeError: Cannot read properties of null (reading 'toNames')
```

2022-11-03 05:07 UTC, Gondragos commented on src/mixins/AnnotationMixin.js
> +    return root.annotationStore?.selected;
```suggestion
    if (isFF(FF_DEV_3391)) {
      const root = getRoot(self);

      // if that's a Tool (they live in separate tree)
      if (root === self) {
        if (self.control) {
          return self.control.annotation;
        } else if (self.obj) {
          return self.obj.annotation;
        }
        return null;
      }

      // if annotation history item selected
      if (root.annotationStore?.selectedHistory) {
        return root.annotationStore.selectedHistory;
      }

      // return connected annotation, not the globally selected one
      return Types.getParentOfTypeString(self, "Annotation");
    }
    const as = self.annotationStore;
    return as?.selectedHistory ?? as?.selected;
```
Just to be sure

2022-11-03 05:10 UTC, Gondragos commented on src/regions/Area.js
> +      const objectName = Tree.cleanUpId(sn.object.name || sn.object);
I'm not sure, but it may be that this change we also would like to wrap into a feature flag.

2022-11-03 05:33 UTC, Gondragos commented on src/mixins/AnnotationMixin.js
> +      return null;
```suggestion
      const as = self.annotationStore;

      return as?.selectedHistory ?? as?.selected;
```

2022-11-03 05:33 UTC, Gondragos commented on src/mixins/AnnotationMixin.js
> +      return null;
This should fix tests

2022-11-04 17:24 UTC, bmartel approved these changes

2022-11-09 14:37 UTC, merged